apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: filtered-app-logging
  namespace: http-logger
spec:
  outputs:
    http:
      url: 'http://http-logger-route-http-logger.apps.awsocp.sandbox2969.opentlc.com/'
