apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
  - ../../base

patchesStrategicMerge:
  - patch-loki-s3-secret.yaml
#  - patch-loki-stack.yaml

