apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
- ../../base

patches:
- path: patch-openshift-logging-ns.yaml
- path: patch-loki-stack.yaml
- path: patch-loki-s3-secret.yaml
