apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleeper
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: sleeper
    server: https://kubernetes.default.svc
  source:
    path: sleeper/base
    repoURL: https://github.com/bryonbaker/openshift-apps
    targetRevision: main
  sources: []
  project: sleeper
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
