apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleeper
  namespace: openshift-gitops
spec:
  destination:
    namespace: sleeper
    server: https://kubernetes.default.svc
  project: sleeper
  source:
    path: sleeper/overlays
    repoURL: https://github.com/bryonbaker/openshift-apps
    targetRevision: HEAD