apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  # generateName: openshift-operators-redhat-
  name: openshift-operators-redhat-loki-og
  namespace: openshift-operators-redhat
spec:
  upgradeStrategy: Default