apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  source:
    path: logging-demo/overlays/bakerapps
    repoURL: https://github.com/bryonbaker/openshift-apps
    targetRevision: main
  sources: []
  project: openshift-logging

