apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github
    mappingMethod: claim
    type: GitHub
    github:
      clientID: <insert client ID>
      clientSecret:
        name: github-oauth-secret
      organizations:
      - OpenShiftAuthz
