apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Configure the Kafka topic
  - logging-cluster.yaml

  # Create the ClusterLogForwarder
  - kafka-filtered-app-logging.yaml
