apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Configure service accounts, roles and secrets
  - collector-sa.yaml
  - role-bindings.yaml

  # Create Operator Instances
  - loki-stack.yaml
  - cluster-log-forwarder.yaml
  - observability-ui-plugin.yaml
