apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openshift-logging-ns.yaml
  - logging-loki-s3-secret.yaml
  - loki-stack.yaml
  - collector-sa.yaml
  - role-bindings.yaml
  - observability-ui-plugin.yaml
  - cluster-log-forwarder.yaml
