apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: filtered-app-logging
  namespace: http-logger
spec:
  managementState: Managed
  inputs:


#     - name: my-app-logs
#       type: application
#       application:
#         includes:
#           - namespace: "sleeper"
    - name: my-audit-logs
      type: audit
      audit:
        sources:
          - kubeAPI
          - openshiftAPI
  outputs:
    - lokiStack:
        authentication:
          token:
            from: serviceAccount
        target: # This is the name of the Loki Stack installed via the Operator
          name: logging-loki
      http:
        url: 'http://http-logger-route-http-logger.apps.awsocp.sandbox2969.opentlc.com/'
        method: POST
      tls:
        ca:
          configMapName: openshift-service-ca.crt
          key: service-ca.crt
      name: logging-http
      type: http
  filters:
  - drop:
    - test:
      - field: .objectRef.namespace
        notMatches: sleeper
    - test:
      - field: .objectRef.resource
        notMatches: virtualmachineinstances
      - field: .objectRef.resource
        notMatches: pods
    - test:
      - field: .verb
        notMatches: create
      - field: .verb
        notMatches: delete
  pipelines:
    - inputRefs:
        - audit
      filterRefs:
        - monitor-namespace
      outputRefs:
        - logging-http
      name: app-logs-pipeline
  serviceAccount:
    name: http-log-collector-sa
