apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Configure service accounts, roles and secrets
  - http-log-collector-sa.yaml
  - role-bindings.yaml
  - cluster-pre-filtered-app-log-forwarder.yaml

  # Create Operator Instances
  - http-logger-dep.yaml
  - http-logger-svc.yaml
  - http-logger-route.yaml
